"""The migrations must actually run - existing merely proves they were written.

The rest of the suite builds its schema with ``Base.metadata.create_all`` because
that is fast and standard. That means nothing else here would notice a broken or
missing migration, so these tests cover that gap directly.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect

from app.database import Base
from app.migrate import alembic_config, upgrade_head

EXPECTED_TABLES = {t.name for t in Base.metadata.sorted_tables}


def _url(tmp_path: Path) -> str:
    return f"sqlite:///{tmp_path / 'migrated.db'}"


def test_migrations_apply_to_an_empty_database(tmp_path):
    url = _url(tmp_path)
    upgrade_head(url)

    tables = set(inspect(create_engine(url)).get_table_names())
    assert EXPECTED_TABLES <= tables, f"missing: {EXPECTED_TABLES - tables}"
    assert "alembic_version" in tables


def test_migrations_leave_no_drift_against_the_models(tmp_path):
    """`alembic check` is the guard against a model change shipping without a
    migration - the failure that otherwise surfaces in production as a 500
    disguised as a CORS error."""
    url = _url(tmp_path)
    upgrade_head(url)

    try:
        command.check(alembic_config(url))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"models and migrations disagree - missing a migration?\n{exc}")


def test_migrations_are_reversible(tmp_path):
    """A migration that cannot be rolled back cannot be deployed confidently."""
    url = _url(tmp_path)
    cfg = alembic_config(url)

    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    remaining = set(inspect(create_engine(url)).get_table_names()) - {"alembic_version"}
    assert not remaining, f"downgrade left tables behind: {remaining}"

    command.upgrade(cfg, "head")
    assert EXPECTED_TABLES <= set(inspect(create_engine(url)).get_table_names())
