"""The migrations must actually run - existing merely proves they were written.

The rest of the suite builds its schema with ``Base.metadata.create_all`` because
that is fast and standard. That means nothing else here would notice a broken or
missing migration, so these tests cover that gap directly.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text as sa_text

from app.database import Base
from app.migrate import alembic_config, upgrade_head

EXPECTED_TABLES = {t.name for t in Base.metadata.sorted_tables}

# the first migration, the one an existing database is stamped with
_BASELINE = "f209a0994828"


def _url(tmp_path: Path) -> str:
    return f"sqlite:///{tmp_path / 'migrated.db'}"


def test_migrations_apply_to_an_empty_database(tmp_path):
    url = _url(tmp_path)
    upgrade_head(url)

    tables = set(inspect(create_engine(url)).get_table_names())
    assert EXPECTED_TABLES <= tables, f"missing: {EXPECTED_TABLES - tables}"
    assert "alembic_version" in tables


def test_migrations_leave_no_drift_against_the_models(tmp_path):
    """`alembic check` is the guard against a model change shipping without a
    migration - the failure that otherwise surfaces in production as a 500
    disguised as a CORS error."""
    url = _url(tmp_path)
    upgrade_head(url)

    try:
        command.check(alembic_config(url))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"models and migrations disagree - missing a migration?\n{exc}")


def test_migrations_are_reversible(tmp_path):
    """A migration that cannot be rolled back cannot be deployed confidently."""
    url = _url(tmp_path)
    cfg = alembic_config(url)

    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    remaining = set(inspect(create_engine(url)).get_table_names()) - {"alembic_version"}
    assert not remaining, f"downgrade left tables behind: {remaining}"

    command.upgrade(cfg, "head")
    assert EXPECTED_TABLES <= set(inspect(create_engine(url)).get_table_names())


# --- adopting a database that predates Alembic --------------------------------


def _make_pre_alembic_db(tmp_path, name="legacy.db"):
    """A database in the state this project's deployments were left in by
    `create_all`: every table present, no alembic_version."""
    import sqlite3

    url = f"sqlite:///{tmp_path / name}"
    command.upgrade(alembic_config(url), _BASELINE)
    con = sqlite3.connect(str(tmp_path / name))
    con.execute("DROP TABLE alembic_version")
    con.commit()
    con.close()
    return url


def test_a_database_that_predates_alembic_is_adopted_not_rebuilt(tmp_path):
    """Running the baseline against it would fail on the first CREATE TABLE with
    "relation already exists" - a crash on boot, which is how this surfaced in
    production."""
    url = _make_pre_alembic_db(tmp_path)
    upgrade_head(url)

    engine = create_engine(url)
    cols = {c["name"] for c in inspect(engine).get_columns("tracker_rows")}
    assert "raw" in cols and "delay_shipment" in cols, "later migrations did not run"
    assert "data" not in cols, "the blob should have been promoted away"


def test_adoption_keeps_the_rows_that_were_already_there(tmp_path):
    import json
    import sqlite3

    url = _make_pre_alembic_db(tmp_path, "withdata.db")
    con = sqlite3.connect(str(tmp_path / "withdata.db"))
    blob = {"buyer_po": "D652", "style_no": "20273308", "colour": "Black",
            "factory_name": "CRIMSON", "buyer_net_price": 9.25, "remarks": "keep me"}
    con.execute(
        "INSERT INTO tracker_rows (match_key,buyer_po,style_no,colour,data,edited_keys,"
        "has_buyer,has_vendor,created_at,updated_at) VALUES (?,?,?,?,?,?,1,1,"
        "datetime('now'),datetime('now'))",
        ("D652|20273308|BLACK", "D652", "20273308", "Black", json.dumps(blob), "[]"),
    )
    con.commit()
    con.close()

    upgrade_head(url)

    engine = create_engine(url)
    with engine.connect() as conn:
        row = conn.execute(
            sa_text("select factory_name, buyer_net_price, remarks from tracker_rows")
        ).one()
    assert row.factory_name == "CRIMSON"
    assert row.buyer_net_price == 9.25
    assert row.remarks == "keep me"


def test_an_unrecognised_schema_is_refused_rather_than_stamped(tmp_path):
    """Stamping a schema we cannot identify would mark it as migrated and leave
    the failure to surface later, somewhere less obvious."""
    import sqlite3

    path = tmp_path / "foreign.db"
    con = sqlite3.connect(str(path))
    con.execute("CREATE TABLE something_else (id INTEGER PRIMARY KEY)")
    con.commit()
    con.close()

    with pytest.raises(RuntimeError, match="does not match the baseline schema"):
        upgrade_head(f"sqlite:///{path}")


def test_an_empty_database_is_built_from_the_migrations(tmp_path):
    """Adoption must not swallow the ordinary case."""
    url = f"sqlite:///{tmp_path / 'fresh.db'}"
    upgrade_head(url)
    assert EXPECTED_TABLES <= set(inspect(create_engine(url)).get_table_names())
