"""baseline schema

Revision ID: f209a0994828
Revises: 
Create Date: 2026-08-21 22:23:21.519925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f209a0994828'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('factory_town', sa.String(length=64), nullable=True),
    sa.Column('port_of_loading', sa.String(length=64), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('terms_of_delivery', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_name'), ['name'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('field_label', sa.String(length=128), nullable=False),
    sa.Column('field_class', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_field_key'), ['field_key'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_confirmation', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=True),
    sa.Column('supplier', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('country_of_payment', sa.String(length=64), nullable=True),
    sa.Column('payment_terms', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('terms_of_delivery', sa.String(length=64), nullable=True),
    sa.Column('factory_town', sa.String(length=64), nullable=True),
    sa.Column('port_of_loading', sa.String(length=64), nullable=True),
    sa.Column('buyer_block', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_header', sa.JSON(), nullable=False),
    sa.Column('size_header', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_orders_created_by_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=False)

    op.create_table('po_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_po', sa.String(length=64), nullable=False),
    sa.Column('season_type', sa.String(length=2), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_po_seasons_assigned_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_seasons'))
    )
    with op.batch_alter_table('po_seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_seasons_buyer_po'), ['buyer_po'], unique=True)

    op.create_table('vendor_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=True),
    sa.Column('supplier', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('country_of_payment', sa.String(length=64), nullable=True),
    sa.Column('payment_terms', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('terms_of_delivery', sa.String(length=64), nullable=True),
    sa.Column('factory_town', sa.String(length=64), nullable=True),
    sa.Column('port_of_loading', sa.String(length=64), nullable=True),
    sa.Column('buyer_block', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_header', sa.JSON(), nullable=False),
    sa.Column('size_header', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_vendor_orders_created_by_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_orders_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_orders'))
    )
    with op.batch_alter_table('vendor_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_orders_order_number'), ['order_number'], unique=False)

    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.String(length=64), nullable=True),
    sa.Column('order_date_d', sa.Date(), nullable=True),
    sa.Column('article', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('colour', sa.String(length=64), nullable=True),
    sa.Column('style_no', sa.String(length=64), nullable=True),
    sa.Column('topup', sa.String(length=32), nullable=True),
    sa.Column('lot', sa.String(length=32), nullable=True),
    sa.Column('garment_code', sa.String(length=32), nullable=True),
    sa.Column('sizes', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('packing_method', sa.String(length=64), nullable=True),
    sa.Column('etd', sa.Date(), nullable=True),
    sa.Column('sleeve_length', sa.String(length=64), nullable=True),
    sa.Column('shoulder_pad', sa.String(length=64), nullable=True),
    sa.Column('hanger_foam', sa.String(length=64), nullable=True),
    sa.Column('composition', sa.String(length=255), nullable=True),
    sa.Column('lining', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('swing_ticket_type', sa.String(length=64), nullable=True),
    sa.Column('label_extra', sa.String(length=64), nullable=True),
    sa.Column('factory', sa.String(length=128), nullable=True),
    sa.Column('store', sa.String(length=32), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_lines_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lines'))
    )
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_lines_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_lines_style_no'), ['style_no'], unique=False)

    op.create_table('vendor_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.String(length=64), nullable=True),
    sa.Column('order_date_d', sa.Date(), nullable=True),
    sa.Column('article', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('colour', sa.String(length=64), nullable=True),
    sa.Column('style_no', sa.String(length=64), nullable=True),
    sa.Column('topup', sa.String(length=32), nullable=True),
    sa.Column('lot', sa.String(length=32), nullable=True),
    sa.Column('garment_code', sa.String(length=32), nullable=True),
    sa.Column('sizes', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('packing_method', sa.String(length=64), nullable=True),
    sa.Column('etd', sa.Date(), nullable=True),
    sa.Column('sleeve_length', sa.String(length=64), nullable=True),
    sa.Column('shoulder_pad', sa.String(length=64), nullable=True),
    sa.Column('hanger_foam', sa.String(length=64), nullable=True),
    sa.Column('composition', sa.String(length=255), nullable=True),
    sa.Column('lining', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('swing_ticket_type', sa.String(length=64), nullable=True),
    sa.Column('label_extra', sa.String(length=64), nullable=True),
    sa.Column('factory', sa.String(length=128), nullable=True),
    sa.Column('store', sa.String(length=32), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_order_id'], ['vendor_orders.id'], name=op.f('fk_vendor_order_lines_vendor_order_id_vendor_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_order_lines'))
    )
    with op.batch_alter_table('vendor_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_order_lines_style_no'), ['style_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_order_lines_vendor_order_id'), ['vendor_order_id'], unique=False)

    op.create_table('tracker_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_key', sa.String(length=255), nullable=False),
    sa.Column('buyer_po', sa.String(length=64), nullable=True),
    sa.Column('style_no', sa.String(length=64), nullable=True),
    sa.Column('colour', sa.String(length=64), nullable=True),
    sa.Column('article', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('edited_keys', sa.JSON(), nullable=False),
    sa.Column('has_buyer', sa.Boolean(), nullable=False),
    sa.Column('has_vendor', sa.Boolean(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=True),
    sa.Column('vendor_order_line_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tracker_rows_created_by_users')),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], name=op.f('fk_tracker_rows_order_line_id_order_lines')),
    sa.ForeignKeyConstraint(['vendor_order_line_id'], ['vendor_order_lines.id'], name=op.f('fk_tracker_rows_vendor_order_line_id_vendor_order_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracker_rows'))
    )
    with op.batch_alter_table('tracker_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracker_rows_buyer_po'), ['buyer_po'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracker_rows_match_key'), ['match_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_tracker_rows_style_no'), ['style_no'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracker_rows_style_no'))
        batch_op.drop_index(batch_op.f('ix_tracker_rows_match_key'))
        batch_op.drop_index(batch_op.f('ix_tracker_rows_buyer_po'))

    op.drop_table('tracker_rows')
    with op.batch_alter_table('vendor_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_order_lines_vendor_order_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_order_lines_style_no'))

    op.drop_table('vendor_order_lines')
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_lines_style_no'))
        batch_op.drop_index(batch_op.f('ix_order_lines_order_id'))

    op.drop_table('order_lines')
    with op.batch_alter_table('vendor_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_orders_order_number'))

    op.drop_table('vendor_orders')
    with op.batch_alter_table('po_seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_seasons_buyer_po'))

    op.drop_table('po_seasons')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))

    op.drop_table('orders')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_field_key'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_name'))

    op.drop_table('vendors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))

    op.drop_table('customers')
    # ### end Alembic commands ###
